### ISSUE TITLE
Allow users to change default file types when decompiling multiple files

### ISSUE THREAD

**Issue by UrGenericName** [ValveResourceFormat/ValveResourceFormat#647] opened 2023-10-14 20:20 UTC
### Is your feature request related to a problem? Please describe.

When individually decompiling materials/models, you get an option for whichever supported file type you'd like to decompile as.  When batch decompiling, you don't get to choose which file type to decompile as, meaning it'll always decompile to the default file type.  _(material's default type is .vmat, and model's default type is .gltf)_

For materials, .vmat works fine for most purposes, but .gltf is honestly not very useful.

### Describe the solution you'd like

Would be super nice to have a setting where I could change the default file types, so I could batch decompile stuff to whichever file types suite my needs.

### Describe alternatives you've considered

Alternatively just changing the default model file type from .gltf to .vmdl would make more sense.

**Comment by xPaw** [comment] 2023-10-16 09:04
> Alternatively just changing the default model file type from .gltf to .vmdl would make more sense.

This just inverts the issue into the other way (what if users want gltf).

I'm thinking one way of solving this is detecting all the unique file types in what user is about to select (so walk the nodes recursively), and then present a dialog with each file type listed, and a dropdown on how they want to export it (same options as in the save dialog when exporting an individual file).

**Comment by xPaw** [comment] 2023-10-16 13:34
Closing as a duplicate of #512

**Comment by xPaw** [comment] 2023-10-16 18:29
Try last unstable build.

**Closed by xPaw** 2023-10-16 18:29 UTC
Labels: enhancement
