### ISSUE TITLE
Counter strike 2 decompile maps brushes converts to static prips after decompile 

### ISSUE THREAD

**Issue by Sirfiwzh** [ValveResourceFormat/ValveResourceFormat#726] opened 2024-02-17 15:06 UTC
### Describe the bug

Hi
I don't know if it's a bug, problem or even a normal thing but when decompile cs2 maps with vrf every brushes turns to static props and losing their collision i mean players can pass through it or grounds losing their collision and player falling down unless if you fill every walkable space with clip.
Do you guys have any idea about how to fix that?
Btw I'm sorry for my bad English 

### What game does this happen in

Counter strike 2 

### Reference file in a Source 2 game

All compiled map files

### Expected behavior

Decompile maps with collided brushes 

### What version of VRF are you using? On what platform?

Windows

**Comment by xPaw** [comment] 2024-02-17 15:07
Duplicate of #648

**Closed by xPaw** 2024-02-17 15:07 UTC
Labels: bug
