### ISSUE TITLE
Unsupported sound file: CVoiceContainerSelector

### ISSUE THREAD

**Issue by deadloxc** [ValveResourceFormat/ValveResourceFormat#803] opened 2024-05-31 20:48 UTC
### Describe the bug

Unable to decompile sound file (sounds/containers/random_weights_container.vsnd_c)

![image](https://github.com/ValveResourceFormat/ValveResourceFormat/assets/171383499/b77e53e7-7f04-46bb-9d2a-4b9e9b4d9921)

### Expected behavior

Should be able to decompile

### Relevant log output or exception with stacktrace

```shell
[02:13:25.714] System.AggregateException: One or more errors occurred. (Unsupported sound file: CVoiceContainerSelector)
 ---> System.IO.InvalidDataException: Unsupported sound file: CVoiceContainerSelector
   at ValveResourceFormat.ResourceTypes.Sound.ConstructFromCtrl(BinaryReader reader, Resource resource) in /_/ValveResourceFormat/Resource/ResourceTypes/Sound.cs:line 200
   at ValveResourceFormat.Resource.Read(Stream input, Boolean verifyFileSize) in /_/ValveResourceFormat/Resource/Resource.cs:line 328
   at GUI.Forms.ExtractProgressForm.ExtractFilesAsync(Queue`1 filesToExtract) in /_/GUI/Forms/ExtractProgressForm.cs:line 347
   at GUI.Forms.ExtractProgressForm.<OnShown>b__21_0() in /_/GUI/Forms/ExtractProgressForm.cs:line 215
   --- End of inner exception stack trace ---
```

### What game does this happen in

Project8/Deadlock

### Reference file in a Source 2 game

sounds/containers/random_weights_container.vsnd_c

### What version of VRF are you using? Test latest dev build.

Latest Build

**Comment by xPaw** [comment] 2024-05-31 20:48
Duplicate of #773

**Closed by xPaw** 2024-05-31 20:48 UTC
Labels: bug
