### ISSUE TITLE
Animate sprite vtex files in gui

### ISSUE THREAD

**Issue by xPaw** [ValveResourceFormat/ValveResourceFormat#447] opened 2022-10-12 12:03 UTC
### Is your feature request related to a problem? Please describe.

In dota, an example file is materials/particle/fire/fire_animated.vtex_c

Create a separate tab and animate the sprite from the sprite data.

**Comment by kristiker** [comment] 2024-03-03 21:27
Old duplicate of #700

**Closed by kristiker** 2024-03-03 21:27 UTC
Labels: enhancement
