### ISSUE TITLE
Vwrld model textures don't look right

### ISSUE THREAD

**Issue by dexelbro** [ValveResourceFormat/ValveResourceFormat#627] opened 2023-09-25 01:58 UTC
### Describe the bug

After decompiling and exporting a CS2 map into gltf, when I import the model into blender the mesh looks fine but the texture colors are wrong.

### What game does this happen in

CS 2

### Reference file in a Source 2 game

All .vwrld map files

### Expected behavior

The textures of the map look the way they do in the game 

### What version of VRF are you using? On what platform?

5.0, Windows 10

**Comment by Lifeismana** [comment] 2023-09-25 02:29
Did you try on latest unstable?
https://vrf.steamdb.info/

**Comment by dexelbro** [comment] 2023-09-25 21:01
yes, same thing

**Comment by kristiker** [comment] 2023-09-29 00:09
Don't expect glTF materials to support Source 2 terrain blend effects out of the box.

Previous discussion: #597

**Comment by xPaw** [comment] 2023-10-08 08:16
Gonna close as duplicate of #639 as that has more info.

**Closed by xPaw** 2023-10-08 08:16 UTC
Labels: bug
