### ISSUE TITLE
Sound preview by clicking on it

### ISSUE THREAD

**Issue by pixeljammed** [ValveResourceFormat/ValveResourceFormat#667] opened 2023-11-13 15:59 UTC
### Is your feature request related to a problem? Please describe.

It's a lot of extra button presses and extra tabs opened just to preview a sound (.vsnd_c)

### Describe the solution you'd like

I would appreciate it if there was an option to immediately preview/play a sound simply by clicking or right clicking on it.

**Comment by xPaw** [comment] 2023-11-13 16:00
Sort of duplicate of #179

**Comment by xPaw** [comment] 2023-11-13 16:08
> please consider adding

Pull requests are always welcome.

**Comment by xPaw** [comment] 2024-04-23 07:36
Fixed by 404f7a79364e4919c6ac8fe905603a858524524f

**Closed by xPaw** 2024-04-23 07:36 UTC
Labels: enhancement
